# render.yaml

services:
  - type: web
    name: jolie-bot
    env: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SUPABASE_URL
        value: https://your-project.supabase.co/rest/v1/memory
      - key: SUPABASE_KEY
        value: your-supabase-secret-key
      - key: GROQ_API_KEY
        value: your-groq-key
